### ISSUE TITLE
I would like to add a DL project of cotton disease prediction using cnn

### ISSUE THREAD

**Issue by Gitesh1209** [pccoeacm/ml-opensource#14]
I have created a Crop disease prediction project, Which predicts the disease of the cotton crop .
How to solve agriculture problems using Artificial Intelligence. Cotton Plant disease prediction.

**Comment by JayeshShelar** [comment]
@Gitesh1209 I have assigned you the issue. You can start working on it.

**Comment by JayeshShelar** [comment]
Merged a PR for this isssue!
