### ISSUE TITLE
Adding a spam classifier

### ISSUE THREAD

**Issue by varunpusarla** [pccoeacm/ml-opensource#5]
Would like to add a spam classifier that takes input from user and specifier whether the input text is spam or not.

**Comment by varunpusarla** [comment]
I want to work on this.

**Comment by JayeshShelar** [comment]
@varunpusarla I have assigned you the issue. You can start working on it!

**Comment by varunpusarla** [comment]
Thanks. I'm working on it.

**Comment by JayeshShelar** [comment]
Added the model for now. Need to do further work for front end.
