### ISSUE TITLE
Leaf Infection Classification

### ISSUE THREAD

**Issue by aniketdhole07** [pccoeacm/ml-opensource#6]
I have created a Leaf Infection Classifier model to detect if Image of any plant leaf is infected or not. I would like to add this in this repo.

**Comment by JayeshShelar** [comment]
> I have created a Leaf Infection Classifier model to detect if Image of any plant leaf is infected or not. I would like to add this in this repo.

@aniketdhole07 I have assigned you the issue. You can start working on it.
